name: CI
on:
  pull_request:
    paths:
    - '.github/workflows/ci.yml'
    - 'deploy/**'
    - 'src/**'

permissions:
  id-token: write
  contents: read

jobs:
  azure:
    name: Azure
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Authenticate to Azure
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ secrets.AZURE_CI_CLIENT_ID }}

    - name: Lint ARM template (Azure Infrastructure)
      uses: azure/arm-deploy@v1
      with:
        deploymentMode: Validate
        resourceGroupName: azure-deprecation-notices-staging
        template: ./deploy/azure-infrastructure.bicep
        parameters: ./deploy/azure-infrastructure.parameters.staging.json

    - name: Lint ARM template (Notice Management)
      uses: azure/arm-deploy@v1
      with:
        deploymentMode: Validate
        resourceGroupName: azure-deprecation-notices-staging
        template: ./deploy/notice-management.bicep
        parameters: ./deploy/notice-management.parameters.staging.json

    - name: Lint ARM template (REST API)
      uses: azure/arm-deploy@v1
      with:
        deploymentMode: Validate
        resourceGroupName: azure-deprecation-notices-staging
        template: ./deploy/rest-api.bicep
        parameters: ./deploy/rest-api.parameters.staging.json

    - name: Lint ARM template (Notifications)
      uses: azure/arm-deploy@v1
      with:
        deploymentMode: Validate
        resourceGroupName: azure-deprecation-notices-staging
        template: ./deploy/notifications.bicep
        parameters: ./deploy/notifications.parameters.staging.json mailchimpBearerToken=CI gmailClientId=CI gmailClientSecret=CI

  solution:
    name: Runtime (Solution)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Solution
      run: dotnet build src/AzureDeprecation.sln --configuration Release