name: Deploy Azure Infrastructure
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Package Azure Infrastructure"]
    branches: [main]
    types: 
      - completed
    
env:
  ARTIFACT_NAME: azure-infrastructure
  OUTPUT_PATH: ${{ github.workspace }}/.output
  ApplicationInsights.Name: azure-deprecation-notices-telemetry${{ env.ENVIRONMENT_RESOURCE_SUFFIX }}
  CosmosDb.Account.Name: azure-deprecation-notices${{ env.ENVIRONMENT_RESOURCE_SUFFIX }}
  CosmosDb.Database.Name: deprecation-db
  CosmosDb.Collection.Name: deprecations
  EventGrid.Topic.Name: azure-deprecation-notices${{ env.ENVIRONMENT_RESOURCE_SUFFIX }}
  LogAnalytics.Name: azure-deprecation-notices-logs${{ env.ENVIRONMENT_RESOURCE_SUFFIX }}
  ServiceBus.Namespace.Name: azure-deprecation-notices${{ env.ENVIRONMENT_RESOURCE_SUFFIX }}

jobs:
  deploy_to_staging:
      name: Deploy to Staging environment
      env:
        AZURE_RESOURCEGROUP_NAME: "azure-deprecation-notices-staging"
        ENVIRONMENT_RESOURCE_SUFFIX: "-staging"
      environment:
        name: azure-infrastructure-staging
      runs-on: ubuntu-latest
      steps:
          # Download artifact
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
            name: ${{ env.ARTIFACT_NAME }}
            path: ${{ env.OUTPUT_PATH }}

          # Login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_STAGING }}

          # Replace tokens in ARM template
      - uses: microsoft/variable-substitution@v1 
        with:
          files: '${{ env.OUTPUT_PATH }}/azure-infrastructure.parameters.json'
        env:
          ApplicationInsights.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          CosmosDb.Account.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          CosmosDb.Database.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          CosmosDb.Collection.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          EventGrid.Topic.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          LogAnalytics.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          ServiceBus.Namespace.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ${{ env.OUTPUT_PATH }}/azure-infrastructure.json
          parameters: ${{ env.OUTPUT_PATH }}/azure-infrastructure.parameters.json