name: Azure Infrastructure (Deploy)
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Azure Infrastructure (Package)"]
    branches: [main]
    types: 
      - completed
    
env:
  ARTIFACT_NAME: azure-infrastructure
  OUTPUT_PATH: ${{ github.workspace }}/.output
  CosmosDb.Database.Name: deprecation-db
  CosmosDb.Collection.Name: deprecations

jobs:
  deploy_to_staging:
      name: Deploy to Staging environment
      env:
        AZURE_RESOURCEGROUP_NAME: "azure-deprecation-notices-staging"
        ENVIRONMENT_RESOURCE_SUFFIX: "-staging"
        ApplicationInsights.Name: azure-deprecation-notices-telemetry-staging
        CosmosDb.Account.Name: azure-deprecation-notices-staging
        EventGrid.Topic.Name: azure-deprecation-notices-staging
        LogAnalytics.Name: azure-deprecation-notices-logs-staging
        ServiceBus.Namespace.Name: azure-deprecation-notices-staging
      environment:
        name: azure-infrastructure-staging
      runs-on: ubuntu-latest
      steps:
          # Download artifact
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow: package-azure-infrastructure.yml
            workflow_conclusion: success
            name: ${{ env.ARTIFACT_NAME }}

          # Login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_STAGING }}

          # Replace tokens in ARM template
      - uses: microsoft/variable-substitution@v1
        with:
          files: '${{ env.ARTIFACT_NAME }}/azure-infrastructure.parameters.json'
        env:
          ApplicationInsights.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          CosmosDb.Account.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          CosmosDb.Database.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          CosmosDb.Collection.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          EventGrid.Topic.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          LogAnalytics.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          ServiceBus.Namespace.Name: ${{ env.AZURE_RESOURCEGROUP_NAME }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          template: ${{ env.ARTIFACT_NAME }}/azure-infrastructure.json
          parameters: ${{ env.ARTIFACT_NAME }}/azure-infrastructure.parameters.json