name: REST API (Deploy)
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["REST API (Package)"]
    branches: [main]
    types: 
      - completed

permissions:
  id-token: write
  contents: read
    
env:
  ARTIFACT_NAME: rest-api
  FUNCTION_PACKAGE_PATH: function

jobs:
  deploy_to_staging:
      name: Deploy to Staging environment
      env:
        AZURE_RESOURCEGROUP_NAME: "azure-deprecation-notices-staging"
        AZURE_FUNCTIONAPP_NAME: azure-deprecation-notices-rest-api-staging
      environment:
        name: rest-api-staging
      runs-on: ubuntu-latest
      steps:
          # Download artifact
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow: package-rest-api
            workflow_conclusion: success
            name: ${{ env.ARTIFACT_NAME }}

          # Login to Azure
      - uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_DEPLOYMENT_STAGING_CLIENT_ID }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          deploymentName: rest-api-run-${{ github.run_number }}
          template: rest-api.json
          parameters: rest-api.parameters.staging.json
      
      - name: Deploy Azure Function
        id: deploy-to-azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.FUNCTION_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

  deploy_to_production:
      name: Deploy to Production environment
      needs: [deploy_to_staging]
      env:
        AZURE_RESOURCEGROUP_NAME: "azure-deprecation-notices"
        AZURE_FUNCTIONAPP_NAME: azure-deprecation-notices-rest-api
      environment:
        name: rest-api-production
      runs-on: ubuntu-latest
      steps:
          # Download artifact
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow: package-rest-api
            workflow_conclusion: success
            name: ${{ env.ARTIFACT_NAME }}

          # Login to Azure
      - uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_DEPLOYMENT_PRODUCTION_CLIENT_ID }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          deploymentName: rest-api-run-${{ github.run_number }}
          template: rest-api.json
          parameters: rest-api.parameters.production.json
      
      - name: Deploy Azure Function
        id: deploy-to-azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.FUNCTION_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
