name: Azure Infrastructure (Deploy)
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Azure Infrastructure (Package)"]
    branches: [main]
    types: 
      - completed

permissions:
  id-token: write
  contents: read
    
env:
  ARTIFACT_NAME: azure-infrastructure

jobs:
  deploy_to_staging:
      name: Deploy to Staging environment
      env:
        AZURE_RESOURCEGROUP_NAME: "azure-deprecation-notices-staging"
      environment:
        name: azure-infrastructure-staging
      runs-on: ubuntu-latest
      steps:
          # Download artifact
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow: package-azure-infrastructure.yml
            workflow_conclusion: success
            name: ${{ env.ARTIFACT_NAME }}

          # Login to Azure
      - uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_DEPLOYMENT_STAGING_CLIENT_ID }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          deploymentName: infrastructure-run-${{ github.run_number }}
          template: azure-infrastructure.json
          parameters: azure-infrastructure.parameters.staging.json

  deploy_to_production:
      name: Deploy to Production environment
      needs: [deploy_to_staging]
      env:
        AZURE_RESOURCEGROUP_NAME: "azure-deprecation-notices"
      environment:
        name: azure-infrastructure-production
      runs-on: ubuntu-latest
      steps:
          # Download artifact
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow: package-azure-infrastructure.yml
            workflow_conclusion: success
            name: ${{ env.ARTIFACT_NAME }}

          # Login to Azure
      - uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_DEPLOYMENT_PRODUCTION_CLIENT_ID }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          deploymentName: infrastructure-run-${{ github.run_number }}
          template: azure-infrastructure.json
          parameters: azure-infrastructure.parameters.production.json
