name: Notice Management (Deploy)
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Notice Management (Package)"]
    branches: [main]
    types: 
      - completed
    
env:
  ARTIFACT_NAME: notice-management
  FUNCTION_PACKAGE_PATH: function

jobs:
  deploy_to_staging:
      name: Deploy to Staging environment
      env:
        AZURE_RESOURCEGROUP_NAME: "azure-deprecation-notices-staging"
        AZURE_FUNCTIONAPP_NAME: azure-deprecation-notices-notice-management-staging
      environment:
        name: notice-management-staging
      runs-on: ubuntu-latest
      steps:
          # Download artifact
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow: package-notice-management.yml
            workflow_conclusion: success
            name: ${{ env.ARTIFACT_NAME }}

          # Login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_STAGING }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: whiteducksoftware/azure-arm-action@v3.3
        with:
          creds : ${{ secrets.AZURE_CREDENTIALS_STAGING }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          templateLocation: notice-management.json
          parameters: notice-management.parameters.staging.json
          overrideParameters: |
            GitHub.Token=${{ secrets.BOT_GITHUB_TOKEN }}
      
      - name: Deploy Azure Function
        id: deploy-to-azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.FUNCTION_PACKAGE_PATH }}/function
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

  deploy_to_production:
      name: Deploy to Production environment
      needs: [deploy_to_staging]
      env:
        AZURE_RESOURCEGROUP_NAME: "azure-deprecation-notices"
        AZURE_FUNCTIONAPP_NAME: azure-deprecation-notices-notice-management
      environment:
        name: notice-management-production
      runs-on: ubuntu-latest
      steps:
          # Download artifact
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow: package-notice-management.yml
            workflow_conclusion: success
            name: ${{ env.ARTIFACT_NAME }}

          # Login to Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: whiteducksoftware/azure-arm-action@v3.3
        with:
          creds : ${{ secrets.AZURE_CREDENTIALS_PRODUCTION }}
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          templateLocation: notice-management.json
          parameters: notice-management.parameters.production.json
          overrideParameters: |
            GitHub.Token=${{ secrets.BOT_GITHUB_TOKEN }}
      
      - name: Deploy Azure Function
        id: deploy-to-azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.FUNCTION_PACKAGE_PATH }}/function
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
