name: Notice Management (Deploy)
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Notice Management (Package)"]
    branches: [main]
    types: 
      - completed

permissions:
  id-token: write
  contents: read
    
env:
  ARTIFACT_NAME: notice-management
  FUNCTION_PACKAGE_PATH: function

jobs:
  deploy_to_staging:
      name: Deploy to Staging environment
      env:
        AZURE_RESOURCEGROUP_NAME: "azure-deprecation-notices-staging"
        AZURE_FUNCTIONAPP_NAME: azure-deprecation-notices-notice-management-staging
      environment:
        name: notice-management-staging
      runs-on: ubuntu-latest
      steps:
          # Download artifact
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow: package-notice-management.yml
            workflow_conclusion: success
            name: ${{ env.ARTIFACT_NAME }}

          # Login to Azure
      - uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_DEPLOYMENT_STAGING_CLIENT_ID }}

        # Deploy ARM template
      - uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          deploymentName: notifice-management-run-${{ github.run_number }}
          template: notice-management.json
          parameters: notice-management.parameters.staging.json GitHub.Token=${{ secrets.BOT_GITHUB_TOKEN }}
      
      - name: Deploy Azure Function
        id: deploy-to-azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.FUNCTION_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

  deploy_to_production:
      name: Deploy to Production environment
      needs: [deploy_to_staging]
      env:
        AZURE_RESOURCEGROUP_NAME: "azure-deprecation-notices"
        AZURE_FUNCTIONAPP_NAME: azure-deprecation-notices-notice-management
      environment:
        name: notice-management-production
      runs-on: ubuntu-latest
      steps:
          # Download artifact
      - name: Download Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow: package-notice-management.yml
            workflow_conclusion: success
            name: ${{ env.ARTIFACT_NAME }}

          # Login to Azure
      - uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id: ${{ secrets.AZURE_DEPLOYMENT_PRODUCTION_CLIENT_ID }}

        # Deploy ARM template
      - uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
          deploymentName: notifice-management-run-${{ github.run_number }}
          template: notice-management.json
          parameters: notice-management.parameters.production.json GitHub.Token=${{ secrets.BOT_GITHUB_TOKEN }}
      
      - name: Deploy Azure Function
        id: deploy-to-azure
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.FUNCTION_PACKAGE_PATH }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
