name: Azure Infrastructure (Package)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - 'deploy/azure-infrastructure.json'
    - '.github/workflows/package-azure-infrastructure.yml'
    
env:
  ARTIFACT_NAME: azure-infrastructure

jobs:
  package:
    name: Package Azure Infrastructure
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: List Deploy folder
      run:  ls deploy
    - name: Publish Azure Function Artifact
      uses: actions/upload-artifact@v1
      with:
          name: ${{ env.ARTIFACT_NAME }}
          path: deploy/azure-infrastructure.json
    - name: Publish ARM template to Artifact
      uses: actions/upload-artifact@v1
      with:
          name: ${{ env.ARTIFACT_NAME }}
          path: deploy/azure-infrastructure.parameters.json
    - name: Publish ARM template to Artifact
      uses: actions/upload-artifact@v1
      with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            deploy/azure-infrastructure.json
            deploy/azure-infrastructure.parameters.json
