name: Azure Infrastructure (Package)
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - 'deploy/azure-infrastructure.json'
    - '.github/workflows/package-azure-infrastructure.yml'
    
env:
  ARTIFACT_NAME: azure-infrastructure

jobs:
  package:
    name: Package Azure Infrastructure
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Publish ARM template to Artifact
      uses: actions/upload-artifact@v1
      with:
          name: ${{ env.ARTIFACT_NAME }}
          path: deploy/azure-infrastructure.json
      # Since tokenization is a pain, so we work around it
    - name: Publish ARM template parameters (Staging) to Artifact
      uses: actions/upload-artifact@v1
      with:
          name: ${{ env.ARTIFACT_NAME }}
          path: deploy/azure-infrastructure.parameters.staging.json
    - name: Publish ARM template parameters (Production) to Artifact
      uses: actions/upload-artifact@v1
      with:
          name: ${{ env.ARTIFACT_NAME }}
          path: deploy/azure-infrastructure.parameters.production.json